In [2]:
import numpy as np

In [3]:
np


<module 'numpy' from '/usr/lib/python3/dist-packages/numpy/__init__.py'>

In [5]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [7]:
np.full(20, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5,
       2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [8]:
x = [1,2,3,4]

In [9]:
xx = np.array(x)

In [10]:
print(xx)

[1 2 3 4]


In [11]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [13]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## Multidimensional arrays

In [14]:
np.zeros([5,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [16]:
n = np.array([
    [1,2,3],
    [3,4,5]

])

In [19]:
n[1][2]

5

In [20]:
n[1,2]

5

In [21]:
n[0]

array([1, 2, 3])

In [22]:
print(n)

[[1 2 3]
 [3 4 5]]


In [23]:
n[0]=[1,1,1]

In [24]:
print(n)

[[1 1 1]
 [3 4 5]]


In [25]:
n[:,1]

array([1, 4])

In [26]:
n[:,1]=[3,5]

In [27]:
print(n)

[[1 3 1]
 [3 5 5]]


In [37]:
#Usa standard distribution
#Se puede especificar la semilla
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [39]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [41]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [43]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [45]:
a = a + 1
a

array([1, 2, 3, 4, 5])

In [46]:
a = a*2
a

array([ 2,  4,  6,  8, 10])

In [47]:
b = (10 + (a*2))**2 / 100

In [48]:
b

array([1.96, 3.24, 4.84, 6.76, 9.  ])

In [49]:
a + b

array([ 3.96,  7.24, 10.84, 14.76, 19.  ])

## Comparison operations

In [50]:
a >= 3

array([False,  True,  True,  True,  True])

In [52]:
a > b

array([ True,  True,  True,  True,  True])

In [53]:
a[a>b]

array([ 2,  4,  6,  8, 10])

In [54]:
a <= b

array([False, False, False, False, False])

In [55]:
a[a>b]

array([ 2,  4,  6,  8, 10])

## Summarizing operations

In [56]:
a


array([ 2,  4,  6,  8, 10])

In [60]:
a.std()

2.8284271247461903